import { LevelThemeOverride } from '../../data/models/LevelThemeModel';

/**
 * 全局默认主题：所有关卡都会继承这里。
 * 分工建议：通用规则改这里；单关差异改同目录 level-XXX.ts。
 */
export const DEFAULT_LEVEL_THEME: LevelThemeOverride = {
    label: 'Default Game Theme',
    background: 'newtheme/bg/chapter1/1',
    tileBase: 'newtheme/tile_base_pink',
    audio: {
        bgm: { path: 'audio/bgm/BGM_ingame', volume: 0.56 },
        sfx: {
            click: { path: 'audio/sfx/click_new', volume: 0.62 },
            match: { path: 'audio/sfx/match_new', volume: 0.66 },
            hint: { path: 'audio/sfx/hint_new', volume: 0.78 },
            shuffle: { path: 'audio/sfx/shuffle_new', volume: 0.78 },
            undo: { path: 'audio/sfx/undo_new', volume: 0.82 },
            win: { path: 'audio/sfx/level_complete_new', volume: 0.68 },
            fail: { path: 'audio/sfx/fail_new', volume: 0.80 },
        },
    },
    effects: {
        boardEnter: {
            enabled: true,
            layerStaggerMax: 0.04,
            jitterMax: 0.06,
            screenTopY: 760,
            offscreenBaseTileHeights: 0.4,
            offscreenJitterTileHeights: 0.6,
            fallDurationMin: 0.18,
            fallDurationMax: 0.26,
            bounce1UpMin: 0.07,
            bounce1UpMax: 0.10,
            bounce1DownMin: 0.05,
            bounce1DownMax: 0.07,
            bounce2UpMin: 0.03,
            bounce2UpMax: 0.05,
            bounce2DownMin: 0.03,
            bounce2DownMax: 0.04,
            bounce1HeightRatio: 0.08,
            bounce2HeightRatio: 0.025,
            bounceHeightRandomness: 0.15,
        },
        shuffle: {
            enabled: true,
            gatherDuration: 0.22,
            holdDuration: 0.18,
            scatterDuration: 0.20,
            staggerMax: 0.10,
            arcMagnitude: 0.70,
            spinTurnsMin: 1,
            spinTurnsMax: 2,
            vortex: {
                enabled: true,
                radius: 700,
                layers: 10,
                maxAlpha: 230,
                expandDuration: 0.10,
                holdDuration: 0.10,
                shrinkDuration: 0.20,
            },
            boardShake: {
                enabled: true,
                steps: [
                    { duration: 0.10, x: 6, y: -3, scaleX: 1.02, scaleY: 0.98 },
                    { duration: 0.10, x: -6, y: 3, scaleX: 0.98, scaleY: 1.02 },
                    { duration: 0.10, x: 5, y: -2, scaleX: 1.02, scaleY: 0.98 },
                    { duration: 0.10, x: -5, y: 2, scaleX: 0.98, scaleY: 1.02 },
                    { duration: 0.10, x: 3, y: -1, scaleX: 1.01, scaleY: 0.99 },
                    { duration: 0.10, x: -3, y: 1, scaleX: 0.99, scaleY: 1.01 },
                    { duration: 0.10, x: 0, y: 0, scaleX: 1, scaleY: 1 },
                ],
            },
        },
        match: {
            enabled: true,
            gravity: -5600,
            emitDuration: 0.62,
            emitters: [
                { totalCount: 230, pool: 'shards', sizeMin: 40, sizeMax: 68, lifeMin: 0.95, lifeMax: 1.35, vxMin: -980, vxMax: 120, vyMin: -120, vyMax: 760, spreadX: 220, spreadY: 170, rotSpeedAmp: 1280 },
                { totalCount: 220, pool: 'shards', sizeMin: 36, sizeMax: 56, lifeMin: 0.85, lifeMax: 1.25, vxMin: -1050, vxMax: 160, vyMin: -180, vyMax: 820, spreadX: 240, spreadY: 190, rotSpeedAmp: 1580 },
                { totalCount: 105, pool: 'sand', sizeMin: 24, sizeMax: 38, lifeMin: 0.75, lifeMax: 1.12, vxMin: -1100, vxMax: 180, vyMin: -220, vyMax: 700, spreadX: 230, spreadY: 180, rotSpeedAmp: 980 },
                { totalCount: 80, pool: 'line', sizeMin: 36, sizeMax: 64, lifeMin: 0.78, lifeMax: 1.15, vxMin: -1120, vxMax: 80, vyMin: -120, vyMax: 740, spreadX: 220, spreadY: 155, rotSpeedAmp: 520, colorTint: { r: 255, g: 255, b: 255 } },
                { totalCount: 35, pool: 'crystal', sizeMin: 26, sizeMax: 42, lifeMin: 0.8, lifeMax: 1.2, vxMin: -920, vxMax: 120, vyMin: -160, vyMax: 620, spreadX: 210, spreadY: 160, rotSpeedAmp: 980, colorTint: { r: 220, g: 235, b: 255 } },
            ],
        },
        combo: {
            enabled: true,
            comboWindowSec: 1.5,
            randomAnimationEnabled: true,
            labelEnabled: true,
            labelPaths: {
                2: 'art/ui/combo_great/spriteFrame',
                3: 'art/ui/combo_excellent/spriteFrame',
                4: 'art/ui/combo_awesome/spriteFrame',
                5: 'art/ui/combo_amazing/spriteFrame',
                6: 'art/ui/combo_perfect/spriteFrame',
            },
            labelStyle: {
                maxWidth: 560,
                startX: 0,
                startY: -50,
                enterY: 30,
                endY: 80,
                enterDuration: 0.18,
                settleDuration: 0.10,
                holdDuration: 0.45,
                exitDuration: 0.30,
                enterScale: 1.2,
                settleScale: 1,
                exitScale: 1.15,
            },
            comboTextCelebration: {
                enabled: true,
                minComboCount: 2,
                texts: ['Great!', 'Unbelievable!'],
                x: 0,
                y: 680,
                width: 620,
                height: 110,
                fontSize: 72,
                textColor: '#FFE934',
                outlineColor: '#6534E8',
                outlineWidth: 8,
                shadowColor: '#4422AA',
                shadowOffsetX: 5,
                shadowOffsetY: -7,
                enterDuration: 0.08,
                holdDuration: 0.86,
                exitDuration: 0.14,
                enterScale: 0.65,
                settleScale: 1,
                exitScale: 0.12,
                starCount: 4,
                starSize: 30,
            },
            randomAnimationInterval: 6,
            randomAnimationNoRepeat: true,
            randomAnimationSpeedScale: 1.1,
            randomAnimations: [
                { name: 'SunsetIslandBelowSlot', spawns: [{ entry: { resource: 'SunsetIsland', animation: 'Appera' }, x: 0, y: 620, size: 350 }] },
                { name: 'WellDoneBirdBelowSlot', spawns: [{ entry: { resource: 'wellDone3Bird', animation: 'WellDone' }, x: 0, y: 620, size: 280 }] },
                { name: 'ClearCelebrateSides', spawns: [
                    { entry: { resource: 'ClearCelebrateBottom', animation: 'Celebration' }, x: -450, y: 580, size: 400 },
                    { entry: { resource: 'ClearCelebrateBottom', animation: 'Celebration' }, x: 450, y:580, size: 400, flipX: true },
                ] },
                { name: 'FlowerBelowSlot', spawns: [{ entry: { resource: 'FlowerInFullBloom', animation: 'Appera' }, x: 0, y: 620, size: 450 }] },
                { name: 'TwoBirdsBelowSlot', spawns: [{ entry: { resource: 'NewFinishedCountTwoBirds', animation: 'IdleTwoBirdsShortVer' }, x: 0, y: 620, size: 350 }] },
                { name: 'TakePhotoBelowSlot', spawns: [{ entry: { resource: 'TakePhoto', animation: 'Appera' }, x: 0, y: 620, size: 350 }] },
            ],
        },
        hubShake: {
            enabled: true,
            levels: {
                small: { up: 0.02, down: 0.02, upDuration: 0.18, holdDuration: 0.40, recoverDuration: 0.22 },
                medium: { up: 0.03, down: 0.02, upDuration: 0.18, holdDuration: 0.40, recoverDuration: 0.22 },
                large: { up: 0.05, down: 0.03, upDuration: 0.18, holdDuration: 0.40, recoverDuration: 0.22 },
            },
            rules: {
                matchedFirst: 'medium',
                matchedCombo: 'large',
                unmatchedCounts: { 4: 'small', 5: 'medium', 6: 'large' },
            },
        },
        mechanics: {
            crow: {
                enabled: true,
                size: 90,
                emoji: '🐦',
                fontSize: 50,
                bodyColor: '#1B1F2A',
                strokeColor: '#FFD54F',
                strokeAlpha: 200,
                strokeWidth: 3,
                flyDurationBase: 0.6,
                flyDurationStep: 0.05,
                delayBaseMs: 200,
                delayStepMs: 120,
            },
            piggy: {
                bodyColor: '#FFA0BD',
                strokeColor: '#FF4D7E',
                strokeWidth: 4,
                radiusRatio: 0.18,
                emoji: '🐷',
                fontScale: 1.2,
            },
            cover: {
                iconAsset: 'art/tile/question',
                fallbackFill: '#111111',
                fallbackStroke: '#FFFFFF',
            },
            golden: {
                iconAsset: 'art/tile/star',
                fallbackFill: '#FFE082',
                fallbackStroke: '#FF9800',
                star: '',
                starScale: 0,
            },
            conveyor: {
                cellSize: 96,
                gap: 12,
                leftInset: 18,
                beltColor: '#8C93A8',
                beltAlpha: 255,
                beltStroke: '#5A6178',
                beltStrokeWidth: 4,
                beltRadius: 54,
                countColor: '#FFE082',
                countFontSize: 28,
            },
        },
    },
};
