import { GAME_CONFIG } from '../../core/Constants';

const SOURCE_WIDTH = 402;
const SOURCE_HEIGHT = 874;

const sx = (value: number): number => Math.round(value * GAME_CONFIG.designWidth / SOURCE_WIDTH);
const sy = (value: number): number => Math.round(value * GAME_CONFIG.designHeight / SOURCE_HEIGHT);
const smin = (value: number): number => Math.round(value * Math.min(GAME_CONFIG.designWidth / SOURCE_WIDTH, GAME_CONFIG.designHeight / SOURCE_HEIGHT));

export const UI_LAYOUT = {
    shared: {
        settingsIcon: {
            x: -460,
            y: 950,
            size: 100,
        },
    },
    home: {
        topBar: {
            leftInset: sx(25),
            topInset: sy(80),
            gap: sx(40),
            buttonSize: smin(88),
            iconScale: 0.46,
        },
        logo: {
            x: sx(0),
            y: sy(200),
            width: sx(990),
            height: sy(702),
            initialScale: 1.2,
            popScale: 1.26,
            finalScale: 1.2,
        },
        playButton: {
            x: sx(0),
            y: sy(-352),
            width: sx(360),
            minWidth: sx(300),
            horizontalPadding: sx(30),
            height: sy(140),
            scale: 0.82,
        },
        avatar: {
            leftInset: sx(36),
            bottomInset: sy(137),
            width: smin(50),
            height: smin(50),
            scale: 1,
        },
    },
    hud: {
        topBar: {
            leftInset: sx(25),
            topInset: sy(80),
            gap: sx(58),
            buttonSize: smin(88),
            iconScale: 0.46,
            titleFontSize: smin(20),
            titleWidth: sx(240),
            titleHeight: sy(56),
        },
        levelSwitch: {
            prevX: sx(-50),
            nextX: sx(50),
            buttonSize: smin(46),
            radius: smin(10),
            fontSize: smin(10),
        },
        boosters: {
            bottomInset: sy(180),
            span: sx(180),
            sidePadding: sx(59),
            buttonSize: smin(192),
            scale: 0.32,
            badge: {
                x: smin(60),
                y: smin(58),
                width: smin(56),
                height: smin(56),
                radius: smin(28),
                fontSize: smin(34),
                bgColor: '#E8412E',
                strokeColor: '#FFFFFF',
                strokeWidth: smin(4),
                textColor: '#FFFFFF',
            },
        },
    },
    map: {
        backgroundPath: 'newtheme/level_select',
        topBar: {
            leftInset: sx(25),
            topInset: sy(80),
            buttonSize: smin(88),
            backScale: 0.44,
            logoX: sx(0),
            logoYOffset: sy(0),
            logoWidth: sx(180),
            logoHeight: sy(128),
            logoScale: 0.46,
        },
        scroll: {
            x: sx(0),
            y: sy(-38),
            horizontalPadding: sx(19),
            maxWidth: sx(446),
            minWidth: sx(164),
            verticalPadding: sy(118),
            maxHeight: sy(640),
            minHeight: sy(410),
            cardHorizontalInset: sx(16),
        },
        card: {
            heightRatio: 0.46,
            minHeight: sy(128),
            maxHeight: sy(178),
            gap: sy(24),
            radius: smin(14),
            bgAlpha: 178,
            titleYRatio: 0.36,
            titleFontSize: smin(18),
            rangeYRatio: 0.22,
            rangeWidth: sx(95),
            rangeHeight: sy(22),
            rangeFontSize: smin(10),
            thumbnailYRatio: -0.16,
            thumbnailWidth: sx(62),
            thumbnailHeight: sy(72),
            thumbnailInnerScale: 0.97,
            thumbnailGap: sx(6),
            thumbnailOverlayAlpha: 56,
            lockIconSize: smin(32),
        },
    },
    transition: {
        overlayAlpha: 72,
        titleY: sy(330),
        titleFontSize: smin(30),
        titleWidthRatio: 0.72,
        titleHeight: sy(92),
        titleLineHeightRatio: 1.05,
        longTitleWordThreshold: 18,
        levelY: sy(290),
        levelFontSize: smin(15),
        levelWidth: sx(120),
        levelHeight: sy(32),
        descY: sy(250),
        descFontSize: smin(13),
        descWidthRatio: 0.78,
        descHeight: sy(82),
        buttonY: sy(-197),
        buttonWidth: sx(320),
        buttonMinWidth: sx(280),
        buttonHorizontalPadding: sx(27),
        buttonHeight: sy(109),
        buttonScale: 0.70,
        buttonFontSizeRatio: 0.37,
        buttonTextYRatio: 0.03,
        buttonPath: 'newtheme/button_continue',
    },
    game: {
        content: {
            horizontalPadding: sx(18),
            maxWidth: sx(350),
            minWidth: sx(164),
        },
        slot: {
            y: sy(260),
            height: sy(105),
            widthRatio: 0.90,
            cellSizeMax: smin(98),
            minGap: smin(8),
            itemScale: 1,
            itemOffsetY: 0,
            visualBottomPadding: sy(30),
        },
        board: {
            y: sy(14),
            height: sy(510),
            safetyGap: sy(0),
            verticalGap: sy(10),
            marginRatio: 0.01,
            /** 棋盘主视觉宽度与上方 hub 槽对齐。 */
            widthRatio: 0.90,
            /** 编辑器手摆 Slot 的最小左右安全边距；1054 宽 Slot 在 1080 设计宽下保持原尺寸。 */
            editableSidePadding: 12,
            /** 竞品常态棋盘：横向 6 个砖、纵向 7 个砖，使用大砖。 */
            normalVisualCols: 6,
            normalVisualRows: 7,
            /** 竞品最大棋盘：横向 7 个砖、纵向 8 个砖，使用小砖；关卡结构不应超过这个尺度。 */
            maxVisualCols: 7,
            maxVisualRows: 8,
            tileStepRatio: 0.94,
            tileSizeMin: 52,
            tileSizeMax: 190,
            referenceCols: 7,
            referenceRows: 8,
            tileScale: 1,
            tileStepScale: 0.84,
            layerStaggerScale: 0.42,
        },
        boosters: {
            visualTopOffset: sy(46),
        },
    },
    modal: {
        settings: {
            width: 880,
            height: 1174,
            scale: 1.3,
            horizontalMargin: sx(14),
            verticalMargin: sy(35),
            backgroundPath: '',
            title: {
                yFromTop: 85,
                width: 420,
                height: 70,
                fontSize: 55,
            },
            close: {
                xInset: 68,
                yFromTop: 112,
                size: 120,
            },
            toggles: {
                yFromTop: 282,
                buttonSize: 150,
                gap: -15,
                offOpacity: 150,
                paths: {
                    music: '',
                    sfx: '',
                    voice: '',
                    vibrate: '',
                    notice: '',
                },
            },
            social: {
                yGapFromToggles: 235,
                labelX: -220,
                labelY: 3,
                labelWidth: 260,
                labelHeight: 70,
                labelFontSize: 50,
                buttonSize: 120,
                fbX: 140,
                friendX: 270,
                iconY: 0,
                fbPath: '',
                friendPath: '',
            },
            actions: {
                yGapFromSocial: 250,
                labelWidth: 560,
                labelHeight: 80,
                languageOffsetY: 60,
                supportOffsetY: -100,
                fontSize: 46,
            },
            links: {
                yFromBottom: 170,
                versionYFromBottom: 90,
                policyX: -255,
                termsX: 240,
                linkWidth: 260,
                linkHeight: 48,
                linkFontSize: 24,
                versionFontSize: 22,
            },
            toast: {
                y: 700,
                width: 600,
                height: 100,
                radius: 24,
                fontSize: 32,
            },
        },
        profile: {
            width: 880,
            height: 1280,
            horizontalMargin: sx(14),
            verticalMargin: sy(35),
        },
    },
} as const;
